### ISSUE TITLE
Change preview to only show the selected test

### ISSUE THREAD

**Issue by daara-s** [dtrifiro/pytest-fzf#24]
When previewing tests with bat, the preview window shows the selected test at the top, but also the next test in the file (if available)
![Screenshot 2024-02-03 at 08 17 29](https://github.com/dtrifiro/pytest-fzf/assets/3807987/7dd6ee4d-9505-48e5-ba95-99c10af4857b)

It would be great if there was an automatic method when previewing to cut off the next test(s), and only show the test selected by fzf.

**Comment by dtrifiro** [comment]
Thanks @daara-s , this was implemented in #27, along with usage of `pygments` formatting of the input test. There might be some slight difference between the preview code and the actual code, which will hopefully be ironed out in the next few releases.  

Let me know if yout hit any issues!
